version: 0.2

phases:
  install: 
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:dev
  post_build:
    commands:
      - aws s3 sync ./build s3://staticwwebsite25997two --content-encoding gzip --debug 
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E1KGSJUWQNOCK5 --paths "/*"

